[UPLOAD] search_flight 완성
wecode-bootcamp-korea/39-2nd-Just-We-Air-backend pull request #6
Opened 2022-12-02 05:43 UTC by applleeee

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 항공편 조회 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- req.query -> 출발 날짜, 출발지, 도착지 정보 받아 해당 조건 만족하는 항공편 검색 후 응답
- 출발 날짜, 출발지, 도착지를 입력하지 않았을 경우, 값이 있지만 적절하지 않은 경우, 조건을 만족하는 항공편이 없는 경우 예외 처리

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항

2022-12-02 08:46 UTC, Kang-kyunghun requested changes

2022-12-02 08:46 UTC, Kang-kyunghun commented on routes/bookingRouter.js
> +bookingRouter.get("/flight-search", bookingController.searchFlight);
```suggestion
bookingRouter.get("/flights", bookingController.searchFlight);
```

2022-12-02 08:46 UTC, Kang-kyunghun commented on controllers/bookingController.js
> +    raiseCustomError("invalid data", 400);
비교하고 있는 숫자들이 어떤 값을 의미하는지 알 수가 없습니다. 상수처리를 하면 좋을 것 같습니다.
그리고 저 값들을 실제로 왜 비교 하는지 코멘트로 남겨주세요.

2022-12-02 08:46 UTC, Kang-kyunghun commented on controllers/bookingController.js
> +  }
빈 결과가 나올 때인 것 같은데, 검색 결과 내용이 없으면 그냥 빈 배열을 주면 좋을 것 같아요.

2022-12-02 08:46 UTC, Kang-kyunghun commented
rebase 해주세요.

2022-12-05 01:57 UTC, applleeee commented on controllers/bookingController.js
> +    raiseCustomError("invalid data", 400);
상수처리라는게 
```
const minDepartureId = 1
```
이렇게 변수로 선언하는 건가요?

2022-12-05 03:44 UTC, Kang-kyunghun requested changes
Test 코드 추가해 주세요.

2022-12-05 03:44 UTC, Kang-kyunghun commented on controllers/bookingController.js
> +  }
제 리뷰에 의하면 해당 코드는 없어도 될 것 같습니다.
그리고 204코드는 no content로 client에서 body를 갖지 못합니다. 이 부분 때문에 프론트와 안 맞을 수 도 있습니다.

2022-12-06 02:42 UTC, Kang-kyunghun commented
고생 하셨습니다.

2022-12-06 02:42 UTC, merged