[Upload] 주문 정보 입력 및 조회 API
wecode-bootcamp-korea/39-2nd-Just-We-Air-backend pull request #9
Opened 2022-12-07 07:11 UTC by Seoya0512

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 주문 정보 입력 및 정보 조회 API 

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 프론트에서 받은 주문 정보 데이터를 백엔드 DB에 저장하는 API 생성 : transaction 사용 
- 결제 관련 정보 조회 API 생성
- unit test 실행 완료 : `users` 미들웨어 mocking 후 테스트 코드 리팩토링 실시, orders 테스트 코드 생성 

<br />

## :: 테스트 결과 이미지

작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지 (users 및 orders 테스트 실행 결과)

![스크린샷 2022-12-07 오후 4 09 04](https://user-images.githubusercontent.com/87962966/206111842-51bdb254-f265-4780-bb3a-a6671fd4f9e0.png)

<br />

## :: 기타 질문 및 특이 사항

2022-12-07 07:16 UTC, Kang-kyunghun requested changes

2022-12-07 07:16 UTC, Kang-kyunghun commented on models/orderDao.js
> +};
이것도 transaction에 같이 있어야 할 것 같습니다.
order가 생겼는데, 승객 정보가 안 들어가면 안 되니까요.

2022-12-08 05:21 UTC, bigfanoftim requested changes

2022-12-08 05:21 UTC, bigfanoftim commented on models/orderDao.js
> +};
경훈님이 말씀해주신 이 부분이 아직 해결되지 않은 것으로 예상됩니다. 피드백에 대한 이해가 어렵다면 Q&A방으로 와주세요!

2022-12-08 07:43 UTC, merged